[deploy]
healthcheckTimeout = 300
restartPolicyMaxRetries = 8
restartPolicyType = "on_failure"
startCommand = "sh -c 'until pg_isready -h $DB_POSTGRESDB_HOST -p $DB_POSTGRESDB_PORT -U $DB_POSTGRESDB_USER; do sleep 1; done && n8n start 2>&1 | tee /tmp/n8n.log'"
